version: '3.0'

services:

  registry:
    container_name: docker-registry
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      # using docker volume /var/lib/docker/volumes/
      - docker-registry-data:/var/lib/registry
      # using local volume bind
      #- ./registry:/var/lib/registry

volumes:
  docker-registry-data: {}
