version: '2'
services:
  postgres:
    container_name: postgres
    image: postgres:9.6
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql/data:/var/lib/postgresql/data
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

  sonarqube:
    container_name: sonarqube
    image: sonarqube:8.1-enterprise-beta
    depends_on:
     - postgres
    networks:
      - sonarnet
    #use jdbc settings using sonar.properties rather environment, as next versions dont support this way
    #environment:
      #- SONARQUBE_JDBC_USERNAME=sonar
      #- SONARQUBE_JDBC_PASSWORD=sonar
      #- SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - ./sonarqube/conf/:/opt/sonarqube/conf/
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/temp:/opt/sonarqube/temp
    restart: always

  nginx:
    container_name: nginx
    image: nginx:1.17
    ports:
      - '80:80'
      - '443:443'
    depends_on:
     - sonarqube
    networks:
      - sonarnet
    volumes:
      - ./nginx:/etc/nginx
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

networks:
  sonarnet:
    driver: bridge
