#### Stage 2: Serve the React application from Nginx 
FROM nginx:1.17.0-alpine

# Copy our custom nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the react build from Stage 1
COPY dist /var/www

# Expose port 3000 to the Docker host, so we can access it 
# from the outside.
EXPOSE 80

ENTRYPOINT ["nginx","-g","daemon off;"]
