version: "2"
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80' #for nexus
      - '5000:5000' #for registry in nexus
    volumes:
      - ./nginx:/etc/nginx/

  nexus:
    image: sonatype/nexus3
    volumes:
      - ./nexus-data:/sonatype-work
  #  ports:
  #    - "8081:8081" #for nexus
  #    - "5000:5000" #for registry in nexus
  
#volumes:
#  nexus-data: {}
